decoder_block: "gemma3"
mlp_activations: ["gelu", "linear"]
normalization_layer_epsilon: 1.0e-6
logits_via_embedding: true
enable_dropout: false
sliding_window_size: 1024
use_post_attn_norm: true
use_post_ffw_norm: true
local_rope_max_timescale: 10000
rope_max_timescale: 1000000
rope_linear_scaling_factor: 8.0
vocab_size: 262144
base_emb_dim: 2560
base_mlp_dim: 10240
base_num_query_heads: 8
base_num_kv_heads: 4
base_num_decoder_layers: 34
head_dim: 256
