decoder_block: "llama2"
mlp_activations: ["silu", "linear"]
enable_dropout: false
logits_via_embedding: false
normalization_layer_epsilon: 1.0e-5
base_emb_dim: 4096
base_mlp_dim: 14336
base_num_query_heads: 32
base_num_kv_heads: 8
base_num_decoder_layers: 32
head_dim: 128
vocab_size: 128256
rope_theta: 500000
