decoder_block: "olmo3"
mlp_activations: ["silu", "linear"]
normalization_layer_epsilon: 1.e-6
enable_dropout: false
vocab_size: 100278
logits_via_embedding: false
normalize_embedding_logits: false
use_qk_norm: true
base_emb_dim: 4096
base_mlp_dim: 11008
base_num_query_heads: 32
base_num_kv_heads: 32
base_num_decoder_layers: 32
head_dim: 128
sliding_window_size: 4096
inhomogeneous_layer_cycle_interval: 4
rope_type: "yarn"
rope_interleave: false
rope_max_timescale: 500000
rope_factor: 8.0
original_max_position_embeddings: 8192
beta_fast: 32.0
beta_slow: 1.0
max_position_embeddings: 65536
rope_attention_scaling: true
rope_truncate: false
